{{# tplrecommend}}
{{> index/floor-header}}
<div class="tpl-recommend clearfix">
	<div class="tpl-body clearfix">
		<div class="tpl-nav">
			<div class="tpl-keywords">
				{{#each keyword}}
				<a class="keywords{{@index}}" title="{{name}}" href="{{href}}"><img class="lazy" data-original="{{img}}"/></a>
				{{/ keyword}}
			</div>
			<div class="tpl-category clearfix">
				{{#each category}}
				<a href="{{href}}">{{name}}</a>
				{{/ category}}
			</div>
		</div>
		<div class="tpl-brands clearfix">
			<ul>
				{{#each brands}}
				<li><a title="{{name}}" href="{{href}}"><img class="lazy" data-original="{{img}}"/></a></li>
				{{/each}}
			</ul>
		</div>
		<div class="tpl-types clearfix">
			<ul>
				{{#each types}}
				<li><a title="{{name}}" href="{{href}}"><img class="lazy" data-original="{{img}}"/></a></li>
				{{/each}}
			</ul>
		</div>
	</div>
	<div class="tpl-products clearfix">
		<ul>
			{{#each products}}
			<li><a href="{{href}}" title="{{name}}"><img class="lazy" data-original="{{img}}"/></a></li>
			{{/each}}
		</ul>
	</div>
</div>
{{/ tplrecommend}}


