{{> index/floor-header}}
<div class="commodity clearfix">
    <div class="commodity-list">
      <ul class="clearfix">
          {{#each imgHot}}
          <li>
             <a href="{{url}}"><div class="commodity-img">
                 {{# tip}}
                 <i class="top">{{.}}</i>
                 {{/ tip}}
                 <img class="lazy" data-original="{{img}}"/></div>
                 <p class="commodity-name">{{name}}</p>
                 <p class="commodity-price"><span>¥{{price}}</span></p>
             </a>
          </li>
          {{/each}}
      </ul>
    </div>
    <div class="commodity-brands clearfix">
        {{#each bands}}
        <a href="{{url}}" title="{{name}}"><img class="lazy" data-original="{{img}}"/></a>
        {{/each}}
    </div>
</div>
